# Generated by Django 4.2.15 on 2024-12-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('size', models.IntegerField()),
                ('department_head', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.FloatField()),
                ('tax', models.FloatField()),
                ('balance', models.FloatField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('departId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='employeemanagementapp.department')),
            ],
        ),
    ]
